# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- name: Copy ISO Files
  hosts: localhost
  any_errors_fatal: true
  roles:
    - copy_iso_files
  tags: copy_iso_files

- name: Setup Controller
  hosts: localhost
  any_errors_fatal: true
  roles:
    - setup
  tags: setup

- name: Preflight
  hosts: localhost
  any_errors_fatal: true
  roles:
    - preflight
  tags: preflight

- name: Setup Kickstart server
  hosts: localhost
  any_errors_fatal: true
  roles:
    - kickstart
  tags: kickstart

- name: Generate Profiles
  hosts: localhost
  any_errors_fatal: true
  roles:
    - profiles
  tags:
    - profiles
    - profile

...
