---

- name: Enable Firewalld Service
  service:
    name: "firewalld"
    state: started
    enabled: true

- name: Add administrator user
  user:
    name: administrator
    shell: /bin/bash
    groups: wheel
    append: yes
  register: administrator_user

- name: Generate RootPw
  command: "openssl passwd -1 {{ root_password | join('==') | b64decode }}"
  register: rootpw
  when: administrator_user.changed

- name: Update administrator user password
  user:
    name: administrator
    password: "{{ rootpw.stdout }}"
  when: administrator_user.changed

- name: update sshd_conf
  template:
    src: templates/sshd_config
    dest: "/etc/ssh/sshd_config"
  register: sshd_config

- name: Bump sshd
  systemd:
    name: sshd
    enabled: yes
    state: restarted
  when: sshd_config.changed

# TODO I'm not sure we need any of this

- name: Get Controller Interface Name
  shell: |
    ip -o addr | grep {{ server_ip }} | awk '{ print $2 }'
  register: controller_interface_name

...
