---
# handlers file for roles/kickstart

- name: check if docker installed
  stat:
    path: "/usr/bin/docker"
  register: docker_stat_result
  listen: "Restart Docker"

- name: Bump docker if firewall changed
  service:
    name: docker
    state: restarted
  when: docker_stat_result.stat.exists
  listen: "Restart Docker"
  ignore_errors: yes
