---

- name: Install rsync
  yum:
    name: rsync
    state: latest

# Verify ISO
- name: check if ESXi iso exists
  stat:
    path: "{{ iso_esxi_pth }}"
    checksum_algorithm: sha256
  register: iso_path_result2

- name: Verify ESXi ISO Checksum
  fail:
    msg: "It appears the iso checksum does not match.  Please redownload the iso from a known good source and verify the iso_checksum is correct in the invetory file."
  when: iso_path_result2.stat.exists and iso_path_result2.stat.checksum != iso_esxi_checksum
  
- name: Mount content to {{ mnt_pth }}
  mount:
    fstype: iso9660
    state: mounted
    opts: loop
    path: "{{ mnt_pth }}"
    src: "{{ iso_esxi_pth }}"
  when:
    - mnt_pth != ""
  register: mounted

- name: Copy dirs from ESXi iso
  synchronize:
    dest: "{{ tftp_dir }}"
    src:  "{{ mnt_pth }}/"
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Unmount iso from {{ mnt_pth }}
  mount:
    state: absent
    path: "{{ mnt_pth }}"

...