---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
  tags: common

- name: Install basic tools
  dnf:
    name:
      - vim
      - wget
      - curl
    state: present
  tags: common
