---
- name: "{{ ansible_distribution }} block"
  block:
    - name: Make default bios {{ kick_cfg }} available
      template:
        src: ks.cfg.j2
        dest: "{{ ks_template_dir }}/ks.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      vars:
        uefi: false

    - name: Make default uefi {{ ansible_distribution }} {{ kick_cfg }} avail
      template:
        src: ks.cfg.j2
        dest: "{{ ks_template_dir }}/uefi/ks.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      vars:
        uefi: true

    - name: Create {{ ansible_distribution }} bios ks for each server
      template:
        src: "ks.cfg.j2"
        dest: "{{ ks_template_dir }}/{{ item }}.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      with_items:
      - "{{ groups['servers'] }}"
      when: hostvars[item].pxe_type == 'bios'
      vars:
        uefi: false

    #- name: Create {{ ansible_distribution }} uefi ks for each server
    #  template:
    #    src: "ks.cfg.j2"
    #    dest: "{{ ks_template_dir }}/uefi/{{ item }}.cfg"
    #    owner: root
    #    group: root
    #    mode: 0644
    #    setype: httpd_sys_content_t
    #  with_items:
    #  - "{{ groups['servers'] }}"
    #  when: hostvars[item].pxe_type == 'uefi'
    #  vars:
    #    uefi: true

    - name: Default ESXi PXE Menus
      template:
        src: "esxi.j2"
        dest: "{{ tftp_dir }}/pxelinux.cfg/default"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp

    #- name: UEFI {{ ansible_distribution }} PXE Menus
    #  template:
    #    src: "grub.cfg.j2"
    #    dest: "{{ tftp_dir }}/uefi/grub.cfg"
    #    owner: root
    #    group: root
    #    mode: 0644
    #    setype: "cobbler_var_lib_t"
    #  register: tftp

    - name: Create ESXi bios pxe menu for each server
      template:
        src: "esxi.j2"
        # This takes the mac address from the inventory file for each node.
        # Replaces the colon with a dash and makes it lower case
        dest: "{{ tftp_dir }}/pxelinux.cfg/01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp
      with_items:
      - "{{ groups['servers'] }}"
      when: hostvars[item].pxe_type == 'bios'

    #- name: Create {{ ansible_distribution }} uefi pxe menu for each server
    #  template:
    #    src: "grub.cfg.j2"
    #    # This takes the mac address from the inventory file for each node.
    #    # Replaces the colon with a dash and makes it lower case
    #    dest: "{{ tftp_dir }}/uefi/grub.cfg-01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}"
    #    owner: root
    #    group: root
    #    mode: 0644
    #    setype: "cobbler_var_lib_t"
    #  register: tftp
    #  with_items:
    #  - "{{ groups['servers'] }}"
    #  when: hostvars[item].pxe_type == 'uefi'
